version: '2.1'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.2
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - '9200:9200'
  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.2
    depends_on:
      - elasticsearch
    ports:
      - '5601:5601'
  app:
    image: node:6
    working_dir: /app
    entrypoint: ['bash', '/app/entrypoint.sh']
    depends_on:
      - elasticsearch
    volumes:
      - './nodejs:/app'
    ports:
      - '9000:9000'
